services:
  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    ports:
      - "5001:8080"
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
  db:
    image: mcr.microsoft.com/mssql/server
    container_name: sql_server_compose
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Password_123#
    restart: always

